POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Amazon",
  "symbol": "AMZN",
  "price": 1000,
  "image": "http://example.com/image.jpg"
}

###
GET http://localhost:3000/assets
